# All prompt building blocks, organized by category.
# Each category has its own pool — blocks are always compatible within it.
# The rule engine in prompt_engine.py handles cross-category camera/lighting logic.
#
# Camera pools are split into two types:
#   PHOTOGRAPHIC: real lens/camera descriptions (portrait, food, street, etc.)
#   COMPOSITIONAL: angle/framing descriptions for illustrated/rendered styles

PROMPT_DATA: dict = {

    # ── PORTRAIT ────────────────────────────────────────────────────────────
    "portrait": {
        "subjects": [
            "a young woman with freckles and piercing green eyes",
            "an elderly fisherman with weathered skin and silver stubble",
            "a teenage girl with braided hair and a distant gaze",
            "a middle-aged man in a rumpled suit, looking exhausted",
            "a child with curly hair and paint-stained hands",
            "a woman wrapped in a shawl, eyes closed, serene expression",
            "a man with a sharp jawline and intense dark eyes",
            "a woman with dramatic red lipstick and a knowing smile",
            "an older woman with silver hair and deep laugh lines",
            "a young man with disheveled hair and tired eyes",
            "a woman with vitiligo, confident gaze directly at lens",
            "a stoic elderly man in traditional clothing",
            "a woman mid-laugh, eyes closed, completely candid",
        ],
        "styles": [
            "photorealistic portrait photography",
            "cinematic portrait with subtle film grain",
            "editorial fashion portrait",
            "documentary black and white photography",
            "high-fashion editorial photography",
            "intimate lifestyle portrait, natural and candid",
            "fine art portrait photography",
        ],
        "cameras": [
            "Canon EF 85mm f/1.4L, shallow depth of field",
            "Hasselblad medium format, 80mm lens",
            "Leica M11, 50mm Summilux, reportage feel",
            "Sony A7R V, 135mm f/1.8 GM, creamy bokeh",
            "shot on film, 85mm portrait lens, subtle grain",
            "Nikon Z9, 105mm macro portrait lens, hyper-sharp",
            "Phase One medium format, exceptional tonal richness",
        ],
        "lighting": [
            "Rembrandt lighting, single key light, deep shadows",
            "soft diffused window light from the left",
            "golden hour backlight, warm rim light on hair",
            "dramatic chiaroscuro, strong contrast",
            "overcast natural light, even and flattering",
            "split lighting, one side illuminated, one in shadow",
            "softbox studio lighting, clean background",
            "hard directional sunlight, graphic shadows",
        ],
        "moods": [
            "melancholic and introspective",
            "confident and powerful",
            "vulnerable and raw",
            "joyful and completely candid",
            "pensive and distant",
            "mysterious and alluring",
            "warm and approachable",
            "stoic and unreadable",
        ],
        "settings": [
            "minimalist white studio background",
            "urban rooftop at dusk, city lights behind",
            "sun-drenched wheat field, golden horizon",
            "dimly lit jazz bar, low ambient glow",
            "industrial warehouse with concrete walls",
            "lush botanical garden, dappled natural light",
            "rain-soaked city street, reflections on pavement",
            "sparse wooden interior, soft light through window",
        ],
        "details": [
            "shallow depth of field, bokeh background",
            "ultra-sharp skin texture, visible pores",
            "subtle film grain, analog feel",
            "perfect retouching, high-end beauty finish",
            "flyaway hairs caught in the light",
            "catchlights in the eyes, lively expression",
            "vignette, darkened corners drawing focus inward",
            "warm color grade, lifted shadows",
        ],
        "parameters": [
            "--ar 2:3 --v 6.1 --style raw",
            "--ar 4:5 --v 6.1 --style raw --q 2",
            "--ar 1:1 --v 6.1 --style raw",
            "--ar 2:3 --v 6.1 --stylize 750",
        ],
        "camera_type": "photographic",
    },

    # ── CHARACTER DESIGN ────────────────────────────────────────────────────
    "character_design": {
        "subjects": [
            "a rogue assassin with a tattered cloak and hidden blades",
            "a cybernetic soldier with a cracked visor and battle scars",
            "an ancient alchemist surrounded by glowing vials and scrolls",
            "a young rebel pilot in a worn flight suit, defiant expression",
            "a mysterious masked figure in ornate ceremonial armor",
            "a shape-shifting trickster deity in mortal disguise",
            "a battle-hardened mercenary with mechanical prosthetic arm",
            "a wise elder monk with glowing runic tattoos",
            "a feral desert nomad wielding a bone spear",
            "a noble vampire in Victorian finery, ageless and cold",
            "a street mage in patched robes with crackling energy hands",
            "a stoic android warrior with exposed circuitry",
        ],
        "styles": [
            "detailed character concept art, game-ready design",
            "stylized character illustration, bold graphic style",
            "realistic character design, film VFX quality",
            "semi-realistic character art, painterly texture",
            "dark fantasy character concept, gritty realism",
            "anime-influenced character design, expressive and dynamic",
        ],
        "cameras": [
            "full body front view, clean character sheet composition",
            "three-quarter view, dynamic hero pose",
            "dramatic low angle looking up at the character",
            "floating mid-shot with strong silhouette",
            "turnaround sheet composition, neutral grey background",
            "dynamic action pose, diagonal framing",
        ],
        "lighting": [
            "dramatic rim light separating subject from dark background",
            "multiple colored light sources, magical atmosphere",
            "strong overhead spotlight, theatrical",
            "soft ambient occlusion lighting, clean and clinical",
            "warm fire light from below, dramatic upward shadows",
            "cool blue backlight with warm orange key fill",
        ],
        "moods": [
            "powerful and imposing",
            "mysterious and unreadable",
            "weary yet determined",
            "villainous with hidden depth",
            "noble and heroic",
            "chaotic and unpredictable",
            "ancient and world-weary",
        ],
        "settings": [
            "neutral gradient background, full character visible",
            "cinematic environment matching the character's world",
            "abstract environment suggesting their backstory",
            "dark void background, all focus on the character",
            "environmental storytelling in the background",
        ],
        "details": [
            "intricate costume details, every material readable",
            "worn and battle-damaged textures on armor and cloth",
            "expressive face showing personality and backstory",
            "detailed accessories, weapons, and signature items",
            "silhouette reads clearly at any distance",
            "color palette cohesion across all elements",
        ],
        "parameters": [
            "--ar 2:3 --v 6.1 --stylize 750",
            "--ar 3:4 --v 6.1 --stylize 800",
            "--ar 1:1 --v 6.1 --stylize 700",
            "--ar 2:3 --v 6.1 --style raw --stylize 500",
        ],
        "camera_type": "compositional",
    },

    # ── FANTASY ─────────────────────────────────────────────────────────────
    "fantasy": {
        "subjects": [
            "a battle-worn elven archer at the edge of a cliff",
            "an ancient dragon coiled around a crumbling stone tower",
            "a young sorceress casting a spell, hands glowing violet",
            "a knight in ornate blackened armor kneeling in rain",
            "a forest spirit made of twisted roots and fireflies",
            "a dwarf blacksmith hammering enchanted steel at the forge",
            "a sea serpent rising from storm-tossed waves",
            "a wandering mage with a staff of living wood",
            "a celestial being descending through parted storm clouds",
            "a rogue assassin cloaked in shadows on a rooftop",
            "a giant frost giant striding across a frozen tundra",
            "a witch stirring a glowing cauldron deep in a dark forest",
        ],
        "styles": [
            "epic fantasy digital painting, highly detailed",
            "dark fantasy oil painting, classical master technique",
            "cinematic fantasy concept art",
            "intricate fantasy illustration, pen and ink with watercolor",
            "grimdark fantasy, muted tones and gritty realism",
            "high fantasy illustration, vibrant and luminous",
            "mythological epic painting in the style of romanticism",
        ],
        "cameras": [
            "wide angle epic composition, dramatic perspective",
            "low angle hero shot, monumental sense of scale",
            "bird's eye view, vast sweeping landscape",
            "dynamic diagonal composition, sense of motion",
            "extreme close-up with epic background softly in focus",
            "panoramic widescreen cinematic framing",
            "Dutch angle, tilted to convey tension and unease",
        ],
        "lighting": [
            "mystical moonlight filtering through ancient trees",
            "volcanic glow and floating ember sparks",
            "bioluminescent magical aura, soft blue-green light",
            "dramatic storm lightning illuminating the scene",
            "golden god rays piercing through dark storm clouds",
            "ethereal mist with an inner pale glow",
            "torchlight and deep shadow in a dungeon corridor",
            "aurora borealis casting colored light across snow",
        ],
        "moods": [
            "epic and awe-inspiring",
            "dark and foreboding",
            "mysterious and otherworldly",
            "triumphant and heroic",
            "ancient and melancholic",
            "tense and full of danger",
            "magical and full of wonder",
        ],
        "settings": [
            "ancient ruined citadel overgrown with vines and moss",
            "volcanic mountain range under a blood-red sky",
            "enchanted forest with glowing mushrooms and fireflies",
            "underwater elven city of crystal spires",
            "frozen tundra with a crumbling ice fortress",
            "floating sky islands connected by rope bridges",
            "dark swamp with twisted dead trees and fog",
            "desert ruins under twin moons and a purple sky",
        ],
        "details": [
            "intricate armor engravings and visible battle damage",
            "magical particles and arcane runes floating in air",
            "dramatic volumetric fog and atmospheric haze",
            "hyper-detailed textures on stone, bark, and foliage",
            "glowing eyes and an ethereal spectral aura",
            "dynamic motion blur on spell effects and fire",
            "richly detailed cloth, leather, and metal materials",
        ],
        "parameters": [
            "--ar 16:9 --v 6.1 --stylize 1000",
            "--ar 3:2 --v 6.1 --stylize 750",
            "--ar 2:3 --v 6.1 --stylize 800",
            "--ar 16:9 --v 6.1 --style raw --stylize 500",
        ],
        "camera_type": "compositional",
    },

    # ── SCI-FI ──────────────────────────────────────────────────────────────
    "sci_fi": {
        "subjects": [
            "an astronaut floating in open space, Earth reflected in the visor",
            "a colossal alien megastructure orbiting a dying star",
            "a lone explorer in an exosuit on a rust-red alien planet",
            "a sleek AI android staring at its reflection",
            "a generation ship breaking through a nebula",
            "a xenobiologist examining a glowing alien organism",
            "a damaged terraforming machine half-buried in alien sand",
            "a cyborg soldier in a devastated urban warzone",
            "first contact: a human facing a towering alien diplomat",
            "a time traveler stepping out of a shimmering portal",
            "a colony ship landing on an ice moon of a gas giant",
        ],
        "styles": [
            "photorealistic sci-fi concept art, cinematic quality",
            "hard science fiction illustration, technically accurate",
            "retrofuturistic space opera painting",
            "digital painting, sci-fi blockbuster concept art",
            "rendered 3D, cinematic sci-fi aesthetic",
            "stark minimalist sci-fi photography style",
        ],
        "cameras": [
            "epic wide angle, sense of cosmic scale",
            "low angle looking up at towering technology",
            "over-the-shoulder shot with vast alien landscape",
            "extreme long shot emphasizing isolation",
            "close-up on face reflected in technological surface",
            "drone perspective over alien terrain",
        ],
        "lighting": [
            "alien sun casting dual shadows in complementary colors",
            "cold blue starlight and distant nebula glow",
            "emergency red lighting, warning strobes",
            "bioluminescent alien flora illuminating the dark",
            "reactor glow, intense white-blue core light",
            "lens flare from a distant star, hard vacuum",
            "holographic display light casting colors on face",
        ],
        "moods": [
            "vast and existentially lonely",
            "tense and on the edge of discovery",
            "awe-inspiring and overwhelming",
            "cold and technologically sterile",
            "hopeful at the frontier of the unknown",
            "dystopian and dehumanizing",
            "mysterious and alien",
        ],
        "settings": [
            "interior of a derelict space station, zero gravity debris",
            "surface of a tidally locked planet, half scorched half frozen",
            "busy spaceport on a densely populated orbital station",
            "alien jungle with bioluminescent megaflora",
            "deep space, accretion disk of a black hole in the distance",
            "underground bunker colony on Mars, artificial lighting",
            "orbiting debris field of a destroyed planet",
        ],
        "details": [
            "volumetric engine exhaust and thruster trails",
            "realistic spacesuit weathering and panel detail",
            "holographic UI elements floating in the environment",
            "physically accurate planet curvature and atmosphere",
            "star field with correct galactic core direction",
            "micro-detail on alien textures and materials",
        ],
        "parameters": [
            "--ar 16:9 --v 6.1 --stylize 800",
            "--ar 2:1 --v 6.1 --stylize 900",
            "--ar 3:2 --v 6.1 --style raw --stylize 600",
            "--ar 16:9 --v 6.1 --style raw",
        ],
        "camera_type": "compositional",
    },

    # ── HORROR ──────────────────────────────────────────────────────────────
    "horror": {
        "subjects": [
            "a figure standing motionless at the end of a dark hallway",
            "a child's hand reaching from under a locked door",
            "an abandoned doll with cracked porcelain face in the attic",
            "a creature made of shadows and broken mirrors",
            "a lighthouse keeper who has not blinked in three days",
            "a mass of writhing tentacles emerging from the floorboards",
            "a woman standing in a flooded basement, staring up",
            "a scarecrow that has moved closer since you last looked",
            "a hospital corridor where all the doors are wrong",
            "an ancient tree in fog, humanoid shapes hanging from branches",
            "a mirror that reflects a room that no longer exists",
        ],
        "styles": [
            "atmospheric horror photography, real and unsettling",
            "dark horror illustration, painterly dread",
            "psychological horror concept art",
            "found footage aesthetic, degraded and raw",
            "gothic horror painting, Victorian dread",
            "body horror digital art, visceral and disturbing",
        ],
        "cameras": [
            "low angle, subject looming overhead threateningly",
            "extreme long shot, subject impossibly far and close simultaneously",
            "Dutch angle, disorienting and wrong",
            "over-the-shoulder looking at something you cannot unsee",
            "close-up on detail that should not exist",
            "wide shot of an empty room that isn't empty",
        ],
        "lighting": [
            "single bare bulb flickering overhead",
            "moonlight through broken windows, harsh and cold",
            "no light source visible, yet everything dimly seen",
            "green-tinged fluorescent light, clinical and nauseating",
            "candle flame throwing jumping shadows",
            "twilight, the moment between visibility and blindness",
            "blood-red light from an unknown source",
        ],
        "moods": [
            "creeping dread, something is wrong but you can't name it",
            "cosmic horror, the scale of wrongness is incomprehensible",
            "psychological terror, the threat is internal",
            "visceral and immediate danger",
            "melancholic and grieving, the horror has already won",
            "oppressive and suffocating",
            "uncanny valley — almost right, deeply wrong",
        ],
        "settings": [
            "a Victorian manor with no electricity and wrong geometry",
            "an abandoned hospital ward, beds still made",
            "a forest at night where the trees lean inward",
            "an underwater structure that should not exist",
            "a suburban house at 3am, every light on, no one home",
            "a carnival after closing, no wind but things moving",
            "a basement with a door that was not there yesterday",
        ],
        "details": [
            "motion blur suggesting movement that stopped too fast",
            "film grain and degradation, like old evidence",
            "negative space that feels occupied",
            "shadows that don't match the light sources",
            "a single detail that is impossible and easy to miss",
            "desaturated color with one wrong hue",
            "extreme depth of field, background too sharp",
        ],
        "parameters": [
            "--ar 16:9 --v 6.1 --stylize 700",
            "--ar 2:3 --v 6.1 --style raw --stylize 500",
            "--ar 4:3 --v 6.1 --stylize 600",
            "--ar 3:2 --v 6.1 --style raw",
        ],
        "camera_type": "compositional",
    },

    # ── SURREALISM ──────────────────────────────────────────────────────────
    "surrealism": {
        "subjects": [
            "a staircase leading to an ocean suspended in mid-air",
            "a woman whose face is a blooming garden",
            "clocks melting over the edge of a bone-dry cliff",
            "a figure made entirely of mirrored glass walking in a forest",
            "a train emerging from a fireplace into a normal living room",
            "an eye the size of a building blinking slowly over a city",
            "a room where gravity is a personal choice",
            "a tree growing from a sleeping giant's chest",
            "a door in the middle of the ocean opening to a desert",
            "a chess game played by mountains against the sea",
            "butterflies made of torn calendar pages in flight",
        ],
        "styles": [
            "surrealist oil painting in the style of Dalí",
            "hyper-realistic surrealist photography composite",
            "dreamlike digital painting, impossible beauty",
            "dark surrealist illustration, ink and shadow",
            "De Chirico-inspired metaphysical painting",
            "Magritte-influenced conceptual surrealism",
        ],
        "cameras": [
            "vast landscape scale, the impossible made mundane",
            "intimate close-up of the absurd detail",
            "symmetric architectural composition, eerie calm",
            "worm's eye view of a scene that defies physics",
            "panoramic sweep of a dreamscape horizon",
            "top-down overhead view of an impossible space",
        ],
        "lighting": [
            "hard midday light as if everything is perfectly normal",
            "theatrical spotlight on the impossible subject",
            "soft golden light making the absurd feel safe",
            "storm light, the sky is wrong but the shadows are right",
            "no clear light source, everything equally illuminated",
            "deep shadows with a single impossible sunbeam",
        ],
        "moods": [
            "uncanny calm, as if this is completely normal",
            "dreamlike and weightless",
            "melancholic and beautiful",
            "darkly humorous",
            "existentially unsettling",
            "quietly magnificent",
        ],
        "settings": [
            "a desert where the sand is made of broken clocks",
            "an infinite library with staircases going nowhere",
            "a city built on the back of a sleeping whale",
            "a sky where the stars are all faces",
            "a room that contains another room that contains the first",
            "a beach where the waves are made of hair",
        ],
        "details": [
            "photorealistic textures on impossible forms",
            "scale is completely wrong in a perfectly consistent way",
            "one element too many that should not logically fit",
            "perfect shadows for objects that cannot cast them",
            "hyper-detailed surface on the impossible subject",
            "color palette is coherent but subtly nauseating",
        ],
        "parameters": [
            "--ar 3:2 --v 6.1 --stylize 1000",
            "--ar 16:9 --v 6.1 --stylize 900",
            "--ar 1:1 --v 6.1 --stylize 800",
            "--ar 4:3 --v 6.1 --stylize 1000",
        ],
        "camera_type": "compositional",
    },

    # ── FOOD ────────────────────────────────────────────────────────────────
    "food": {
        "subjects": [
            "a steaming bowl of ramen with perfectly soft-boiled egg",
            "a rustic sourdough loaf with a cracked, floured crust",
            "a chocolate lava cake with melting center and vanilla ice cream",
            "fresh oysters on crushed ice with lemon and mignonette",
            "a colorful grain bowl with roasted vegetables and tahini",
            "a layered cake with buttercream roses and fresh berries",
            "a charcuterie board with aged cheese, cured meats, and honey",
            "a single perfect espresso in a small ceramic cup",
            "fresh pasta draped over a wooden rolling pin, flour dusted",
            "a stack of fluffy pancakes with maple syrup pouring over",
            "a vibrant sushi platter with pickled ginger and wasabi",
            "a whole roasted chicken with herbs and caramelized citrus",
            "a vibrant acai bowl with colorful tropical toppings",
        ],
        "styles": [
            "editorial food photography, magazine quality",
            "rustic and artisan food styling",
            "minimalist fine dining plating photography",
            "moody dark food photography",
            "bright and airy food blog photography",
            "overhead flat lay food photography",
            "close-up macro food photography",
        ],
        "cameras": [
            "overhead shot, 50mm lens, f/8, tack sharp",
            "45-degree angle, 100mm macro lens, shallow DOF",
            "extreme close-up macro, f/2.8, fine detail",
            "three-quarter view, 85mm lens, natural perspective",
            "flat lay overhead, wide to show full table scene",
            "eye-level shot, 50mm, intimate and direct",
        ],
        "lighting": [
            "soft natural light from a window to the left",
            "diffused studio strobe, soft and even fill",
            "dramatic side light with deep food shadows",
            "backlit with a warm glow through the dish",
            "golden hour ambient light, warm and inviting",
            "overcast soft light, no harsh shadows",
        ],
        "moods": [
            "warm and appetizing, makes you hungry",
            "luxurious and indulgent",
            "fresh and healthy, vibrant and lively",
            "cozy and comforting, homemade feel",
            "elegant and refined, fine dining",
            "dark and moody, dramatic and artistic",
        ],
        "settings": [
            "weathered oak farm table with linen napkin",
            "white marble kitchen counter with fresh herbs",
            "rustic ceramic plate on a slate surface",
            "white linen tablecloth in a bright restaurant",
            "dark moody surface with aged wood background",
            "minimal concrete surface with scattered sea salt",
            "surrounded by raw ingredients and fresh herbs",
        ],
        "details": [
            "steam gently rising from the hot dish",
            "glistening glaze and a delicate sauce drizzle",
            "fresh herb garnish and microgreens on top",
            "condensation drops on a cold glass beside the dish",
            "golden caramelized edges and crispy texture",
            "artistic sauce spill, intentional imperfection",
            "scattered sea salt flakes catching the light",
        ],
        "parameters": [
            "--ar 1:1 --v 6.1 --style raw",
            "--ar 4:5 --v 6.1 --style raw --q 2",
            "--ar 3:2 --v 6.1 --stylize 400",
            "--ar 4:5 --v 6.1 --stylize 300",
        ],
        "camera_type": "photographic",
    },

    # ── PRODUCT PHOTOGRAPHY ─────────────────────────────────────────────────
    "product_photography": {
        "subjects": [
            "a luxury perfume bottle on a reflective black surface",
            "a minimal wristwatch against brushed steel background",
            "a skincare serum bottle with dewy water droplets",
            "a pair of premium headphones on a marble pedestal",
            "a glass whiskey bottle with amber liquid, oak background",
            "a high-end sneaker floating in space, clean white background",
            "a sleek smartphone with a dramatic reflection",
            "a leather wallet with stitching detail, warm studio light",
            "a ceramic coffee mug with steam, minimal props",
            "a luxury fountain pen on raw linen, close detail",
            "a protein powder tub in a dramatic gym environment",
        ],
        "styles": [
            "commercial product photography, clean and sellable",
            "luxury brand product photography, aspirational",
            "editorial product photography, editorial magazine",
            "lifestyle product photography in context",
            "minimalist product photography, all white",
            "dark moody product photography, dramatic",
        ],
        "cameras": [
            "100mm macro lens, f/8, tack sharp product detail",
            "medium format camera, 80mm, incredible tonal range",
            "tilt-shift lens, perfect plane of focus control",
            "50mm, eye-level product shot, natural perspective",
            "overhead flat lay, 35mm, full product visible",
            "close-up macro, extreme surface detail",
        ],
        "lighting": [
            "clean two-light studio setup, perfectly controlled",
            "single softbox from 45 degrees, product shadows visible",
            "backlit product with rim separation from background",
            "dramatic side light emphasizing surface texture",
            "lightbox setup, perfectly even and shadowless",
            "gradient background light, product center stage",
        ],
        "moods": [
            "premium and aspirational",
            "clean and trustworthy",
            "dramatic and desirable",
            "minimal and sophisticated",
            "warm and artisan",
            "technical and precise",
        ],
        "settings": [
            "pure white seamless infinity background",
            "brushed steel and glass studio surface",
            "dark slate with product reflection",
            "warm wood and marble lifestyle context",
            "outdoor lifestyle environment matching product purpose",
            "abstract colored gradient background",
        ],
        "details": [
            "perfect reflections with no distracting elements",
            "surface texture absolutely sharp, no motion blur",
            "product logo readable and correctly lit",
            "no dust, no smudges, pristine product surface",
            "color accuracy, product matches physical object",
            "symmetrical composition, balanced visual weight",
        ],
        "parameters": [
            "--ar 1:1 --v 6.1 --style raw --q 2",
            "--ar 4:5 --v 6.1 --style raw",
            "--ar 3:2 --v 6.1 --style raw --stylize 300",
            "--ar 4:3 --v 6.1 --style raw",
        ],
        "camera_type": "photographic",
    },

    # ── EDITORIAL FASHION ───────────────────────────────────────────────────
    "editorial_fashion": {
        "subjects": [
            "a model in an oversized blazer in an empty parking lot",
            "a fashion editorial with structured geometric clothing",
            "a model in motion, fabric blurring with movement",
            "a couple in matching earth-tone outfits in a desert",
            "a model in a trench coat under a neon sign at night",
            "a seated model in avant-garde styling, direct eye contact",
            "a model with architectural silhouette against a white wall",
            "a group of models in a derelict building, layered styling",
            "a model in a bold yellow coat against grey concrete",
            "a model lying in a wildflower field, couture gown",
        ],
        "styles": [
            "editorial fashion photography, high-end magazine",
            "conceptual fashion editorial, artistic and bold",
            "street editorial, candid and energetic",
            "minimalist fashion photography, clean lines",
            "dark editorial, dramatic and moody",
            "vintage editorial, 90s film aesthetic",
            "high concept fashion story, surreal",
        ],
        "cameras": [
            "medium format, 80mm, clean and extremely detailed",
            "35mm film, candid reportage energy and grain",
            "Canon 5D, 50mm prime, full body editorial shot",
            "telephoto compression, 200mm, isolated subject",
            "wide 24mm for environmental editorial context",
            "Fujifilm grain simulation, cinematic editorial feel",
        ],
        "lighting": [
            "harsh editorial flash against bright daylight",
            "location natural light, late afternoon sun",
            "dramatic mixed lighting, neon and daylight",
            "clean studio strobe, sharp editorial shadows",
            "overexposed bleached high-key editorial look",
            "golden backlight creating a strong silhouette",
        ],
        "moods": [
            "bold and directional, high impact",
            "cool and detached, high fashion",
            "energetic and dynamic",
            "sophisticated and minimal",
            "avant-garde and experimental",
            "nostalgic and cinematic",
        ],
        "settings": [
            "raw industrial space with exposed brick and steel",
            "empty parking garage with fluorescent lights",
            "luxury hotel lobby with marble floors",
            "rooftop with city skyline at blue hour",
            "empty highway stretching into the desert",
            "brutalist concrete architecture, stark geometry",
            "overgrown abandoned building, reclaimed by nature",
        ],
        "details": [
            "fabric movement and fine textile texture",
            "strong graphic shadow patterns across subject",
            "precise composition with deliberate negative space",
            "intentional model expression and hand placement",
            "cohesive color palette throughout the frame",
            "layered styling with visible accessory detail",
        ],
        "parameters": [
            "--ar 4:5 --v 6.1 --style raw",
            "--ar 2:3 --v 6.1 --style raw --q 2",
            "--ar 3:4 --v 6.1 --stylize 500",
            "--ar 16:9 --v 6.1 --style raw",
        ],
        "camera_type": "photographic",
    },

    # ── STREET PHOTOGRAPHY ──────────────────────────────────────────────────
    "street_photography": {
        "subjects": [
            "an old man playing chess alone in a rain-soaked park",
            "a street vendor's hands counting coins at dusk",
            "two strangers sharing an umbrella, not speaking",
            "a child running toward a puddle, arms out",
            "a musician performing to an empty street at midnight",
            "a commuter asleep on a night train, face in window",
            "a woman reading on fire escape steps, city below",
            "a protest crowd with signs blurring in motion",
            "a neon-lit street crossing in the rain, bodies in motion",
            "a delivery worker resting on their bike between orders",
            "an empty diner at 4am, one customer at the counter",
        ],
        "styles": [
            "documentary street photography, candid and honest",
            "black and white street photography, high contrast",
            "color street photography, vivid and saturated",
            "reportage photography, journalistic and raw",
            "fine art street photography, composed and deliberate",
            "infrared street photography, dreamlike tones",
        ],
        "cameras": [
            "Leica Q2, 28mm, hyperfocal zone focus, decisive moment",
            "Fujifilm X100V, 35mm equivalent, compact and discreet",
            "shot on film, Kodak Tri-X pushed to 3200",
            "Ricoh GR, 28mm, snap focus, hip shot angle",
            "Sony A7C, 35mm f/1.8, lightweight documentary kit",
            "Nikon FM2, 50mm, manual focus, pure analog",
        ],
        "lighting": [
            "overcast flat light, even tones, no harsh shadows",
            "rainy night, neon reflections on wet pavement",
            "harsh midday sun, graphic black shadows",
            "golden hour, long shadows, warm city light",
            "mixed artificial light, color temperature clash",
            "blue hour, city lights coming on, dusk balance",
            "underexposed shadow with single beam of light",
        ],
        "moods": [
            "quietly poetic, a moment between moments",
            "energetic and alive, the city at full pulse",
            "lonely in a crowd",
            "hopeful and human",
            "gritty and documentary real",
            "nostalgic and fading",
            "tense and on the edge of something",
        ],
        "settings": [
            "Tokyo at rush hour, Shibuya crossing",
            "New York subway platform, late at night",
            "Paris market street, early morning setup",
            "Hong Kong street market, neon and rain",
            "a small town main street, Sunday emptiness",
            "Istanbul Grand Bazaar, vendors and tourists",
            "Havana sidewalk, faded color and heat",
        ],
        "details": [
            "motion blur on moving subjects, static background",
            "film grain heavy, 3200 ISO feel",
            "strong graphic contrast, deep blacks, blown whites",
            "reflection in wet asphalt doubling the scene",
            "decisive moment captured — gesture peak",
            "background out of focus but legible and meaningful",
        ],
        "parameters": [
            "--ar 3:2 --v 6.1 --style raw",
            "--ar 2:3 --v 6.1 --style raw",
            "--ar 16:9 --v 6.1 --style raw --stylize 300",
            "--ar 1:1 --v 6.1 --style raw",
        ],
        "camera_type": "photographic",
    },

    # ── ARCHITECTURE ────────────────────────────────────────────────────────
    "architecture": {
        "subjects": [
            "a brutalist concrete tower under dramatic storm clouds",
            "a Japanese wooden temple surrounded by autumn maples",
            "a glass and steel skyscraper reflecting a sunset",
            "an ancient Roman aqueduct crossing a green valley",
            "a Zaha Hadid-esque flowing white structure in the desert",
            "a medieval stone cathedral interior, vaulted ceiling",
            "a parametric wooden pavilion in a public park",
            "a minimalist white villa cantilevered over a cliff",
            "a traditional Moroccan riad courtyard with tile and fountain",
            "an underground metro station with mosaic ceilings",
            "a decommissioned industrial factory transformed into a museum",
        ],
        "styles": [
            "architectural photography, professional and precise",
            "fine art architectural photography, dramatic and composed",
            "documentary architectural photography",
            "aerial architectural photography",
            "interior architectural photography",
            "black and white architectural photography",
        ],
        "cameras": [
            "tilt-shift 24mm, perfect vertical correction",
            "ultra-wide 14mm, dramatic spatial distortion",
            "medium format 32mm, maximum resolution and tonal range",
            "drone photography, aerial perspective",
            "50mm, natural perspective, no distortion",
            "Linhof view camera, technical perfect geometry",
        ],
        "lighting": [
            "golden hour side light, textures revealed in raking light",
            "blue hour, interior lights glowing against twilight sky",
            "dramatic storm light, clouds moving fast overhead",
            "overcast flat light, pure form without distraction",
            "harsh midday, graphic shadows from deep reveals",
            "interior window light shafts cutting through space",
            "moonlit building, long exposure, star trail background",
        ],
        "moods": [
            "monumental and imposing",
            "serene and meditative",
            "dynamic and forward-looking",
            "historical and enduring",
            "intimate and human scale",
            "austere and minimal",
        ],
        "settings": [
            "isolated in a vast natural landscape",
            "dense urban context, surrounded by the city",
            "reflected in a still body of water",
            "surrounded by construction scaffolding, under-built",
            "overgrown and reclaimed by nature",
            "seen from an unusual rooftop vantage point",
        ],
        "details": [
            "perfectly straight verticals, no lens distortion",
            "material texture in sharp relief: concrete, glass, stone",
            "human scale element showing building proportion",
            "sky HDR blended, detail in highlights and shadows",
            "foreground element framing the building",
            "reflections and interplay between inside and outside",
        ],
        "parameters": [
            "--ar 16:9 --v 6.1 --style raw --q 2",
            "--ar 3:2 --v 6.1 --style raw",
            "--ar 4:3 --v 6.1 --style raw --stylize 300",
            "--ar 2:3 --v 6.1 --style raw",
        ],
        "camera_type": "photographic",
    },

    # ── INTERIOR DESIGN ─────────────────────────────────────────────────────
    "interior_design": {
        "subjects": [
            "a Japandi living room with linen sofa and bonsai",
            "a New York loft with exposed brick and industrial lighting",
            "a Scandinavian bedroom with white linen and birch furniture",
            "a maximalist library with floor-to-ceiling books and velvet",
            "a Moroccan riad bathroom with zellige tile and brass fittings",
            "a minimalist Japanese tea room with tatami and shoji screens",
            "a French country kitchen with terracotta and open shelves",
            "a dark moody dining room with candlelight and artwork",
            "a coastal beach house living room, bleached wood and linen",
            "a modern brutalist home interior, raw concrete and oak",
        ],
        "styles": [
            "architectural interior photography, professional staging",
            "lifestyle interior photography, warm and lived-in",
            "editorial interior photography, magazine spread quality",
            "CGI interior visualization, photorealistic render",
            "moody interior photography, dramatic and atmospheric",
        ],
        "cameras": [
            "wide angle 24mm, full room visible, no distortion",
            "tilt-shift lens, perfect vertical lines, pro interior style",
            "35mm, natural perspective, intimate room feel",
            "medium format, maximum tonal richness",
            "drone interior overhead, room layout from above",
        ],
        "lighting": [
            "soft diffused natural window light, morning",
            "warm afternoon light casting long shadows",
            "dramatic side light through plantation shutters",
            "multiple practical light sources, layered warm glow",
            "overcast flat light, product-accurate colors",
            "blue hour exterior light combining with interior warmth",
        ],
        "moods": [
            "warm and inviting, feel of home",
            "cool and minimal, calm and precise",
            "luxurious and aspirational",
            "cozy and intimate",
            "fresh and airy, morning energy",
            "moody and atmospheric, evening comfort",
        ],
        "settings": [
            "urban apartment with city views through large windows",
            "rural farmhouse with exposed beams and open fire",
            "coastal property with ocean light flooding in",
            "mountain chalet with stone fireplace and timber",
            "converted industrial space with raw materials",
        ],
        "details": [
            "perfect styling with intentional props and plants",
            "layered textures: linen, wool, ceramic, oak",
            "shadow patterns from window grilles on the floor",
            "art on walls correctly lit and readable",
            "soft reflections in polished floors",
            "scatter cushions and throws naturally arranged",
        ],
        "parameters": [
            "--ar 4:3 --v 6.1 --style raw --q 2",
            "--ar 16:9 --v 6.1 --style raw",
            "--ar 3:2 --v 6.1 --style raw --stylize 300",
            "--ar 1:1 --v 6.1 --style raw",
        ],
        "camera_type": "photographic",
    },

    # ── NATURE & LANDSCAPES ─────────────────────────────────────────────────
    "nature_landscapes": {
        "subjects": [
            "a lone pine tree on a cliff above a fjord at sunrise",
            "a thunderstorm building over a flat Kansas wheat plain",
            "a waterfall dropping into a jungle pool, mist rising",
            "sand dunes in the Sahara, wind-carved perfect ridgelines",
            "a glacial lake turquoise and still, reflected mountains",
            "a mangrove forest at low tide, roots like arches",
            "the Milky Way over a high-altitude volcanic crater",
            "autumn birch forest, leaves in full golden peak color",
            "a sea stack at high tide under breaking storm waves",
            "cherry blossoms in full bloom over a reflecting pool",
            "lava flow entering the ocean, steam explosion",
        ],
        "styles": [
            "landscape photography, professional and dramatic",
            "fine art nature photography",
            "documentary nature photography",
            "aerial landscape photography",
            "long exposure landscape photography",
            "infrared landscape photography, ethereal white foliage",
        ],
        "cameras": [
            "ultra-wide 16mm, sweeping landscape, dramatic sky",
            "50mm, natural human perspective on landscape",
            "telephoto 400mm, compressed distant peaks",
            "tilt-shift for selective focus across the landscape",
            "medium format panoramic, maximum resolution",
            "drone, aerial top-down or perspective",
        ],
        "lighting": [
            "golden hour, first light, long shadows and warm tones",
            "blue hour pre-dawn, landscape saturated and cool",
            "stormy dramatic sky with single shaft of light",
            "midday summer sun, hard shadows and vivid color",
            "full moon, long exposure, silver landscape",
            "aurora borealis, green and purple sky over dark land",
            "fog lifting at sunrise, layers of atmosphere",
        ],
        "moods": [
            "vast and humbling in its scale",
            "serene and timeless",
            "dramatic and powerful, nature uncontrolled",
            "intimate and quietly beautiful",
            "wild and untouched",
            "meditative and still",
        ],
        "settings": [
            "Dolomites, jagged rock spires above a meadow",
            "Scottish Highlands, peat bog and heather",
            "Patagonian steppe, wind-blasted and empty",
            "Cappadocia, balloon-dotted volcanic landscape",
            "Faroe Islands, cliff grass above Atlantic grey",
            "Namib Desert, fog over ancient orange dunes",
        ],
        "details": [
            "foreground wildflowers in sharp focus, horizon blurred",
            "long exposure water, silky smooth motion blur",
            "star point sharpness in Milky Way sky",
            "graduated neutral density blend, sky and land exposed",
            "mist and atmospheric perspective creating depth layers",
            "rain drops on lens creating intentional bokeh orbs",
        ],
        "parameters": [
            "--ar 16:9 --v 6.1 --style raw --q 2",
            "--ar 3:1 --v 6.1 --style raw --stylize 500",
            "--ar 3:2 --v 6.1 --style raw",
            "--ar 2:1 --v 6.1 --stylize 600",
        ],
        "camera_type": "photographic",
    },

    # ── ANIMALS & WILDLIFE ──────────────────────────────────────────────────
    "animals_wildlife": {
        "subjects": [
            "a Bengal tiger wading through a monsoon river",
            "a humpback whale breaching at sunset, spray catching light",
            "a wolf pack on a snowy ridge, breath visible in cold air",
            "a leopard sleeping draped over an acacia branch",
            "a bald eagle diving at speed, talons forward",
            "a polar bear mother and cub on fractured sea ice",
            "a mantis shrimp in a coral crevice, iridescent color",
            "a meerkat standing sentinel at dawn, Kalahari behind",
            "an elephant family crossing a dusty savanna",
            "a hummingbird frozen mid-hover at a hibiscus flower",
            "a great white shark breaching the surface",
            "a snow leopard on a Himalayan rock ledge",
        ],
        "styles": [
            "wildlife photography, National Geographic quality",
            "fine art wildlife photography",
            "underwater wildlife photography",
            "aerial wildlife photography",
            "documentary wildlife photography, raw and honest",
            "macro wildlife photography, insects and small creatures",
        ],
        "cameras": [
            "600mm f/4 telephoto, compressed background, animal isolated",
            "400mm f/2.8, creamy bokeh, animal portrait",
            "100-400mm zoom, versatile tracking, wildlife in action",
            "underwater housing with fisheye lens, coral reef context",
            "drone, aerial perspective on animal movement",
            "macro lens 100mm, insect-scale details",
        ],
        "lighting": [
            "golden hour savanna light, rim light on fur",
            "soft overcast light, even and flattering for fur detail",
            "dramatic storm light with break in the clouds",
            "dappled forest light through tree canopy",
            "backlit water droplets, animal emerging from river",
            "harsh midday African sun, graphic shadow patterns",
            "blue underwater light, sunbeams from surface above",
        ],
        "moods": [
            "powerful and primal",
            "tender and intimate, mother and young",
            "tense and predatory, the moment before",
            "serene and undisturbed, pure wild nature",
            "playful and full of life",
            "endangered and urgent",
        ],
        "settings": [
            "Serengeti at migration time, dust and movement",
            "Arctic tundra, white expanse and isolation",
            "Amazon river at flood season, canopy reflected",
            "kelp forest off California, filtering light",
            "Borneo rainforest canopy, humid and layered",
            "Yellowstone geothermal area, alien landscape",
        ],
        "details": [
            "individual fur, feather, or scale detail sharp",
            "catchlight in the animal's eye, alive and aware",
            "motion blur on fast-moving limbs, body in focus",
            "habitat context readable but not distracting",
            "breath or water vapor visible in cold or humid air",
            "behavioral moment that tells a story",
        ],
        "parameters": [
            "--ar 3:2 --v 6.1 --style raw --q 2",
            "--ar 16:9 --v 6.1 --style raw",
            "--ar 4:3 --v 6.1 --style raw --stylize 400",
            "--ar 2:3 --v 6.1 --style raw",
        ],
        "camera_type": "photographic",
    },

    # ── HISTORICAL SCENES ───────────────────────────────────────────────────
    "historical_scenes": {
        "subjects": [
            "Roman legionaries on the march in a Gallic forest",
            "a Viking longship making landfall at dawn",
            "samurai warriors dueling in a burning castle corridor",
            "Egyptian workers hauling stone blocks at Giza",
            "a medieval marketplace crowded with merchants and animals",
            "Napoleon and his generals studying maps before battle",
            "a gold rush prospector panning a California river",
            "factory workers in an 1890s industrial steel mill",
            "an Aztec temple ceremony at sunrise",
            "WWI soldiers going over the top at dawn",
            "a Renaissance painter's atelier, model posing",
        ],
        "styles": [
            "historical oil painting, academic realism",
            "cinematic historical photography style, desaturated",
            "dramatic history painting, romantic movement",
            "documentary historical illustration",
            "photorealistic CGI historical reconstruction",
            "Renaissance-style chiaroscuro painting",
        ],
        "cameras": [
            "wide panoramic establishing the historical scene",
            "low angle making figures monumental and heroic",
            "documentary close-up, intimate and immediate",
            "overhead aerial view of the historical battlefield",
            "Dutch master composition, dark background, lit subject",
        ],
        "lighting": [
            "torchlight and fire, the primary light sources of the era",
            "dramatic overcast sky, diffused grey-green light",
            "low winter sun, long shadows and pale warmth",
            "candlelit interior, warm amber glow and darkness",
            "harsh midday battle light, graphic and hard",
            "morning mist on a historical landscape",
        ],
        "moods": [
            "epic and historically significant",
            "intimate and human despite the scale",
            "brutal and honest about the cost",
            "ceremonial and formal",
            "chaotic and immediate",
            "melancholic and retrospective",
        ],
        "settings": [
            "ancient city at its height of power",
            "battlefield at the crucial moment",
            "royal court interior, power and ceremony",
            "rural landscape unchanged for centuries",
            "harbor at the departure of an expedition",
            "a humble dwelling that history forgot",
        ],
        "details": [
            "period-accurate costume and material detail",
            "historically correct tools, weapons, and artifacts",
            "aging and wear on all surfaces, no anachronisms",
            "appropriate technology for the exact era",
            "faces with personality, not generic extras",
            "environmental storytelling of the specific time",
        ],
        "parameters": [
            "--ar 16:9 --v 6.1 --stylize 700",
            "--ar 3:2 --v 6.1 --stylize 800",
            "--ar 4:3 --v 6.1 --style raw --stylize 500",
            "--ar 2:3 --v 6.1 --stylize 750",
        ],
        "camera_type": "compositional",
    },

    # ── MYTHOLOGY & LEGENDS ─────────────────────────────────────────────────
    "mythology_legends": {
        "subjects": [
            "Zeus hurling a lightning bolt from a stormy Olympus",
            "Medusa's gaze turning a warrior to stone",
            "Odin and his ravens on the World Tree Yggdrasil",
            "a kitsune fox spirit emerging from a Shinto shrine at night",
            "Poseidon rising from a storm-wracked sea",
            "the Phoenix reborn from its own ashes",
            "Anubis weighing a soul's heart against a feather",
            "the Valkyries riding across a battlefield at dusk",
            "Anansi the spider god weaving the stories of the world",
            "a Tengu warrior perched on a mountain peak at dawn",
            "Cú Chulainn in his battle frenzy, warp spasm contorting him",
        ],
        "styles": [
            "epic mythological oil painting, classical grandeur",
            "ancient Greek vase painting style, black figures",
            "cinematic mythology concept art",
            "Pre-Raphaelite mythological painting, rich detail",
            "Japanese ukiyo-e woodblock mythology style",
            "dramatic romantic mythology painting",
        ],
        "cameras": [
            "monumental low angle, gods filling the sky",
            "wide epic landscape with divine figure as focal point",
            "dynamic diagonal composition, divine conflict",
            "bird's eye view, human scale against divine",
            "intimate close-up on divine face, all-knowing eyes",
        ],
        "lighting": [
            "divine light emanating from the deity themselves",
            "storm and lightning, the wrath of gods",
            "golden light of Olympus, warm and otherworldly",
            "moonlight and torch, ancient ritual night scene",
            "underwater light filtering from above, sea god domain",
            "fire and ember, forge of Hephaestus",
        ],
        "moods": [
            "awe-inspiring and divine in scale",
            "ancient and eternal",
            "wrathful and overwhelming",
            "sorrowful and tragic, mortal against fate",
            "triumphant, the hero ascendant",
            "mysterious, the veil between worlds thin",
        ],
        "settings": [
            "Mount Olympus above the clouds, divine realm",
            "the Underworld, shadows and judgment",
            "a sacred grove where mortals dare not tread",
            "a legendary battlefield from the age of heroes",
            "a divine palace of impossible beauty",
            "the primordial ocean before creation",
        ],
        "details": [
            "divine iconography and symbolic attributes of the deity",
            "epic scale shown through tiny humans in the scene",
            "mythological creatures and symbols correctly depicted",
            "timeless quality, belonging to no specific century",
            "material richness: gold, marble, divine light",
        ],
        "parameters": [
            "--ar 16:9 --v 6.1 --stylize 900",
            "--ar 3:2 --v 6.1 --stylize 1000",
            "--ar 2:3 --v 6.1 --stylize 800",
            "--ar 4:3 --v 6.1 --stylize 900",
        ],
        "camera_type": "compositional",
    },

    # ── CYBERPUNK ───────────────────────────────────────────────────────────
    "cyberpunk": {
        "subjects": [
            "a street hacker jacked into a neural port in a rain-soaked alley",
            "a corporate enforcer in powered exo-armor blocking a slum entrance",
            "a geisha android with exposed servos under cracked porcelain skin",
            "a black-market surgeon working by neon light in a basement clinic",
            "a rebel data courier running across rooftops with a chip in her neck",
            "a drone swarm controlled by a blind operator with optical implants",
            "a yakuza boss whose face is half chrome, half scarred flesh",
            "a child AI vendor selling bootleg personalities in a night market",
        ],
        "styles": [
            "photorealistic cyberpunk photography, cinematic",
            "cyberpunk digital painting, neon and shadow",
            "cinematic cyberpunk concept art",
            "retrofuturist cyberpunk illustration, 80s anime influence",
            "dark cyberpunk noir photography style",
        ],
        "cameras": [
            "low angle in a neon-lit alley, rain on the lens",
            "extreme wide angle, towering megastructure overhead",
            "tight close-up on cybernetic implant detail",
            "over-the-shoulder tracking shot feeling",
            "drone perspective over the sprawling megacity",
            "surveillance camera angle, grainy and distorted",
        ],
        "lighting": [
            "rain-wet neon reflections, magenta and cyan",
            "single overhead sodium lamp in a dark alley",
            "holographic advertisement light cycling across face",
            "fire barrel glow in a dark slum courtyard",
            "corporate tower floodlights cutting down into the slum",
            "internal LED implant glow, bioluminescent veins",
        ],
        "moods": [
            "gritty and dystopian, humanity barely hanging on",
            "frenetic and overwhelming, sensory overload",
            "lonely in the most densely populated place on Earth",
            "dangerous and transactional, trust no one",
            "beautiful in its decay, neon over garbage",
            "tense and paranoid, always watched",
        ],
        "settings": [
            "Chiba City alleyway market, cables overhead, neon everywhere",
            "elevated highway above the slums, rain always falling",
            "corporate arcology lobby, clean and terrifying",
            "underground black market, hidden below the grid",
            "rooftop garden commune, analog resistance space",
            "flooded basement level, city's forgotten underbelly",
        ],
        "details": [
            "rain on every surface, reflective and wet",
            "neon kanji signs and holographic ads layered overhead",
            "chrome and carbon fiber, worn and repaired many times",
            "visible data cables and jury-rigged tech everywhere",
            "facial implants and subdermal tech visible under skin",
            "layer of exhaust haze and neon-lit smog",
        ],
        "parameters": [
            "--ar 16:9 --v 6.1 --stylize 900",
            "--ar 9:16 --v 6.1 --stylize 800",
            "--ar 3:2 --v 6.1 --style raw --stylize 600",
            "--ar 4:5 --v 6.1 --stylize 750",
        ],
        "camera_type": "compositional",
    },

    # ── ABSTRACT ART ────────────────────────────────────────────────────────
    "abstract_art": {
        "subjects": [
            "a spiral of liquid color dissolving into white space",
            "geometric planes intersecting at impossible angles",
            "brushstrokes as thick as sculpture catching raking light",
            "color fields bleeding into each other at the horizon",
            "fragmented forms suggesting a face without depicting one",
            "a web of fine gold line on absolute black",
            "texture built up in layers until it becomes landscape",
            "motion frozen in paint, centrifugal energy",
            "the space between two shapes as the primary subject",
        ],
        "styles": [
            "abstract expressionism, gestural and raw",
            "geometric abstraction, precise and mathematical",
            "color field painting, meditative and expansive",
            "lyrical abstraction, fluid and emotive",
            "hard-edge abstraction, clean graphic forms",
            "abstract photography, pure shape and light",
        ],
        "cameras": [
            "extreme close-up macro, texture as landscape",
            "overhead flat, composition on pure white surface",
            "tight crop removing all contextual reference",
            "long exposure motion blur, subject unrecognizable",
            "multiple exposure layering forms together",
        ],
        "lighting": [
            "raking side light revealing every texture ridge",
            "diffused even light, pure color no distraction",
            "dramatic spotlight creating extreme chiaroscuro",
            "backlight making form translucent and glowing",
            "natural light changing throughout exposure",
        ],
        "moods": [
            "emotionally raw and unmediated",
            "serene and meditative",
            "turbulent and energetic",
            "coldly intellectual, a problem solved in color",
            "joyfully chaotic",
            "melancholic, the feeling without the object",
        ],
        "settings": [
            "context-free, pure formal elements",
            "studio with all reference removed",
            "close enough that setting is irrelevant",
            "a surface that becomes a world",
        ],
        "details": [
            "impasto texture casting its own shadows",
            "color relationships as the primary meaning",
            "the edge between forms as important as the forms",
            "scale only revealed by a single reference point",
            "the mark of the hand, process made visible",
        ],
        "parameters": [
            "--ar 1:1 --v 6.1 --stylize 1000",
            "--ar 4:3 --v 6.1 --stylize 1000",
            "--ar 3:4 --v 6.1 --stylize 900",
            "--ar 16:9 --v 6.1 --stylize 1000",
        ],
        "camera_type": "compositional",
    },

    # ── VEHICLES & MACHINES ─────────────────────────────────────────────────
    "vehicles_machines": {
        "subjects": [
            "a 1960s Ferrari Testa Rossa on a rain-wet mountain road",
            "a steam locomotive at full speed through winter landscape",
            "a WWII Spitfire in a dogfight over the English Channel",
            "a massive container ship in a storm off Cape Horn",
            "a motocross bike mid-air over a desert jump",
            "a vintage NASA Saturn V rocket on the launchpad at night",
            "a Formula 1 car exiting a tunnel onto a sun-drenched straight",
            "a rusted abandoned combine harvester in a field",
            "a submersible exploring a deep ocean trench",
            "a military helicopter over urban combat at dusk",
            "a hypercar prototype in a wind tunnel test",
        ],
        "styles": [
            "automotive photography, commercial and dramatic",
            "editorial vehicle photography, magazine feature",
            "fine art automotive photography",
            "documentary industrial photography",
            "cinematic vehicle photography, film still quality",
            "technical illustration of mechanical systems",
        ],
        "cameras": [
            "panning shot, 1/60s, subject sharp, background blurred",
            "wide angle 16mm, vehicle filling the foreground",
            "telephoto 400mm, vehicle compressed against backdrop",
            "helicopter to helicopter aerial tracking shot",
            "low angle ground-level, vehicle heroic overhead",
            "macro on mechanical detail, engineering as sculpture",
        ],
        "lighting": [
            "golden hour, warm light along the vehicle's flanks",
            "dramatic cloudy sky, diffused and moody",
            "studio photography, multiple controlled lights",
            "headlights on at dusk, dramatic self-illumination",
            "harsh midday sun, hard shadows in panel gaps",
            "night photography, city lights and vehicle reflections",
        ],
        "moods": [
            "powerful and kinetic, energy barely contained",
            "elegant and refined, design as art",
            "industrial and honest, form follows function",
            "nostalgic and romanticized",
            "technical and precise",
            "wild and dangerous, speed as a feeling",
        ],
        "settings": [
            "mountain pass, hairpin road, dramatic drop",
            "salt flats at speed record attempt, heat shimmer",
            "urban night environment, city as backdrop",
            "factory floor, industrial context",
            "abandoned airstrip, lone vehicle in vast space",
            "historic racetrack, worn tarmac and tire marks",
        ],
        "details": [
            "wheel spin or motion blur showing speed",
            "reflections of landscape in paintwork",
            "mechanical detail: engine, gearbox, suspension",
            "driver or pilot expression visible through glass",
            "exhaust, vapor, or tire smoke in the scene",
            "surface light traveling the length of the bodywork",
        ],
        "parameters": [
            "--ar 16:9 --v 6.1 --style raw --q 2",
            "--ar 3:2 --v 6.1 --style raw",
            "--ar 4:3 --v 6.1 --style raw --stylize 400",
            "--ar 2:1 --v 6.1 --style raw --stylize 500",
        ],
        "camera_type": "photographic",
    },

    # ── CINEMATIC STORYTELLING ──────────────────────────────────────────────
    "cinematic_storytelling": {
        "subjects": [
            "a detective alone in a neon-lit rain-soaked office",
            "a child watching a rocket launch from a car roof at night",
            "two strangers on opposite sides of a train window at night",
            "a soldier returning to a door they left years ago",
            "an astronaut eating alone in a habitat on another world",
            "a woman packing a suitcase, the door behind her open",
            "a man looking at old photographs in an empty childhood home",
            "a crowd cheering, one person standing still and silent",
            "a lighthouse keeper signaling into a dark and empty sea",
        ],
        "styles": [
            "cinematic film still, anamorphic lens look",
            "neo-noir photography, high contrast and shadow",
            "golden age Hollywood cinematography style",
            "European arthouse cinema visual language",
            "documentary cinema vérité style",
            "blockbuster cinematography, commercial epic look",
        ],
        "cameras": [
            "anamorphic 2.39:1 widescreen, oval bokeh and flares",
            "35mm film print grain, warm and tactile",
            "Steadicam tracking, intimate and following",
            "static wide shot, character small in environment",
            "extreme close-up on face, micro-expression",
            "overhead crane shot, establishing the human in the world",
        ],
        "lighting": [
            "motivated practical light sources only, naturalistic",
            "magic hour, last light, everything golden and fleeting",
            "hard noir, venetian blind shadow across face",
            "fog-diffused light, mood over information",
            "interior practical lamps warm against cold blue window",
            "single hard key light with dark fill, classic cinematography",
        ],
        "moods": [
            "a story that happened just before this frame",
            "quiet grief that doesn't ask for sympathy",
            "the weight of a decision not yet made",
            "wistful, looking back at something you can't return to",
            "tense, the silence before something changes forever",
            "hopeful in a way that feels earned and fragile",
        ],
        "settings": [
            "a diner at 3am, fluorescent light, two people not talking",
            "a car interior at night, headlights on a dark road",
            "an airport terminal, departure gate, one person waiting",
            "a childhood bedroom, adult revisiting it empty",
            "a rooftop in summer, the city cooling down",
            "a hospital waiting room, the news not yet arrived",
        ],
        "details": [
            "anamorphic lens flares on practical light sources",
            "cinematic color grade: teal shadows, orange skin tones",
            "shallow depth of field, background a soft impressionist blur",
            "production design visible in every prop and surface",
            "actor's hands as expressive as their face",
            "the decisive frame — not the moment, the moment after",
        ],
        "parameters": [
            "--ar 2.39:1 --v 6.1 --style raw --stylize 600",
            "--ar 16:9 --v 6.1 --style raw --stylize 500",
            "--ar 3:2 --v 6.1 --style raw",
            "--ar 16:9 --v 6.1 --stylize 700",
        ],
        "camera_type": "compositional",
    },
}
